language: php
os: linux
dist: xenial

notifications:
  email: false

services:
  - docker

php:
  - 7.0

matrix:
  fast_finish: true
  include:
  - name: "Coding standard check"
  - name: "E2E tests"
    script:
      - npm install jest --global
      - npm run docker:up
      - npm run test:e2e
    after_script:
      - npm run docker:down

branches:
  only:
    - trunk

before_install:
  - nvm install lts/erbium
  - nvm install 10

install:
  - npm install
  - composer install

script:
  - vendor/bin/phpcs
